language: node_js
node_js:
- '8'
dist: trusty
sudo: false
install:
- npm install
script:
- npm run code-check
- npm run test
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  skip_cleanup: true
  api_key:
    secure: RLGaav71EOhBKabshWrG63hcBlJvB8ARWub6wcNmyo2Kt+1i53kMwkUu9+W2vRZROhcfq9PrLTKdDdgrqRbPxbvU0lbbgomJi+WevOFBPi5XyTkPx79X9JUFyduq3KkbQ5yg2FvvFpYxzQo/6+LnKUbFPDJDo+ziFy2kEedc9l0mgID1WTbn78QjHGioXnAWwtYwXRfVV2bmFxtPkCT4qPrqJMqv0N0hLW/j3PaJpt+iJL4juhI8qkBqgOzeyPqVx2CAdo3Naft4q4w/qo4hgkPM+JTWh4ugUce/tY5PQlSDv+k3KkhoVwYwJPS+UVzfiWJFuJQ4oZ1O5JO4TsORtBerCbm3Hx0g+gGpHUDFLpUjSXZDKwiPP2jqHvb38bND5L2wutGLgOmPkEAGJJ8OhyPChD1gZk1UnA6bX/XYCXz42JaC2h4Vo6Wo90JLHpzSItLiLrZzKH6FPxnnaBIFiaid4cVqudtVqoHuUyd89Pd2omdxtVJ2JS+w66TqcTTBVvdgK+sugKffF7j6Ws/rqTL2RrqeeGYA3yWWB+h0kwtjtYl7qZjRI2F1JBY25+QNWYMHBofYM4lCOepQzm2kPScSJ4q1c3DWdilVQKQ9txvsoapQpJHqG1b8rPai3JcleGvgVMS7o0IH9x7DYB1/5/5St184jzHnD4M/OqOtNYI=
  on:
    branch: master
    repo: Cimpress-MCP/edie-processors
